### ISSUE TITLE
Support Throwable

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-php#101]
It would be good if notifyException would support Throwable.

**Comment by kattrali** [comment]
This is a great idea, @GrahamCampbell. I'll be looking into making `notifyException` work well with PHP7, as well as some options for preserving backwards compatibility. Any suggestions are also welcome.

**Comment by cmstone** [comment]
It seems that the only way to preserve the compatibility between 5.x and 7.x is to remove the parameter type declaration from the function definition.  7.x Errors and Exceptions implement Throwable interface which has the same methods as the 5.x Exception class

**Comment by kattrali** [comment]
Thanks for the report, @GrahamCampbell. An updated version should be out later today with a fix.
