### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-php#102]
The first error I saw after upgrading:

```
Uncaught TypeError: Argument 3 passed to Bugsnag_Error::fromPHPException() must be an instance of Exception, instance of Error given, called in Bugsnag/Client.php on line 417 and defined in Bugsnag/Error.php:32

Stack trace: #0 Bugsnag/Client.php(417): Bugsnag_Error::fromPHPException(Object(Bugsnag_Configuration), Object(Bugsnag_Diagnostics), Object(Error))
#1 Bugsnag_Client->exceptionHandler(Object(Error))
#2 [internal function]: HandleException(Object(Error))
#3 {main} thrown
```

Which is an issue caused by this: https://secure.php.net/manual/en/function.set-exception-handler.php#refsect1-function.set-exception-handler-parameters

**Comment by nWidart** [comment]
Same thing for the `ParseError`.

**Comment by kattrali** [comment]
Updated support should be a new version later today. Thanks for the reports, @xPaw, @nWidart!

**Comment by nWidart** [comment]
Awesome! Thank you very much! :smile:

**Comment by kattrali** [comment]
Happy to help!

**Comment by loopj** [comment]
:tada:

**Comment by claygorman** [comment]
I am still having this issue " Uncaught TypeError: Argument 1 passed to Bugsnag_Error::setPHPException() " today with latest files.

**Comment by TomKita** [comment]
@claygorman +1
