### ISSUE TITLE
Type Hint errors are suppressed

### ISSUE THREAD

**Issue by wshafer** [bugsnag/bugsnag-php#108]
Hey guys,

It seems that Type hint errors are being suppressed.   Example:

```php
class a
{
    public function test(a $class)
    {
        echo 'I should never make it here.';
    }
}

$test = new a();
$test->test(new \StdClass()); //This should throw an error
```

Expected: PHP Error
Result: 'I should never make it here.'

This is happening on the master branch.

**Comment by kattrali** [comment]
Very odd. Thank you for the report, @wshafer. Taking a look.
