### ISSUE TITLE
BugSnag lib is a performance bottleneck

### ISSUE THREAD

**Issue by aleemb** [bugsnag/bugsnag-php#114]
The Client can be very detrimental to performance because it tries to report the error within the same request cycle. This means that if I have an innocuous error, visitors to my site will suffer from delayed page load times -- until the error is reported to BugSnag via curl.

In the best case scenario, this delay is equivalent to the time required to aggregate and report the errors to the BugSnag service. In the worse cases, the BugSnag service can have high latency but still be fast, or have low latency but be slow to respond, or be down altogether in which case the page won't render to the visitors until the BugSnag curl request times out.

Another direct implication is that offline testing is totally messed up because every request must time out before continuing.

I am unable to justify putting this in my production code at the moment. Would have been nice if BugSnag provided support for syslog so this could be done out of band.

Maybe you could check for `pcntl_fork` support and leverage that for `curl_exec`?

**Comment by tuupola** [comment]
I think this is why https://github.com/bugsnag/bugsnag-agent exists. Never used it myself though.

**Comment by aleemb** [comment]
I was hoping for a ready, out-of-the-box solution such as [ReactPHP](http://reactphp.org/) or similar. Syslog support would be ideal.

Installing a daemon isn't ideal but it does provide a solution, thanks for the pointer.

**Comment by aleemb** [comment]
I installed the agent and still see a considerable performance impact when I set bugsnag to handle my errors versus when I don't. The agent is setup correctly and proxying all errors to bugsnag service.

**Comment by GrahamCampbell** [comment]
The way I get around this issue is to push the logs to a queue and have the logging done async by a queue worker.

**Comment by aleemb** [comment]
The queue setup is something I wanted to avoid altogether especially as I am trying out a bunch of Error Reporting services and is yet another container to manage.

Ideally syslog support would be far easier and portable across all applications. It would require BugSnag to open up IP/Ports though which is why I imagine they don't have that setup. LogEntries and PaperTrail both support SysLog bug unfortunately their dashboards leave much to be desired.

**Comment by tuupola** [comment]
Logentries and Papertrail are for log management and analysis. Bugsnag is for exception reporting. These are two different things. I do not know if it is feasible to submit exception traces overs syslog. Even though [RFC](https://tools.ietf.org/html/rfc5424) does not limit the maximum length of the message for example rsyslog truncates messages at 2097 characters. Looking at the [notifier api](https://github.com/bugsnag/bugsnag-notifier-api) that limit is reached quite fast.

**Comment by aleemb** [comment]
I read about the UDP solution in another issue but it will still degrade page load performance (for that matter any synchronous network requests within an existing client request is a bad idea).

I tried `bugsnag-agent` but for whatever reason, the page loads time became 2-3x longer when I added something as innocuous as `$foo = UNDEFINED_CONST`. I suspect it's something to do with this library as opposed to the agent itself though I haven't had a chance to look into it - -I was hoping to pay for a service and solve this problem in under a day :)

The correct approach is to do this asynchronously outside the current request (queues, syslog, ReactPHP or some daemon/agent). I dont' know if `pcntl_fork` is the right approach as fire-and-forget forked process can result in zombie/orphaned processes and potential memory leak.

I am still confounded that all the people using this lib (and for that matter PHP implementations of other major exception reporting SaaS) have involuntarily degraded their page load performance in error scenarios.

I suppose everyone will follow suit once the first of these exception reporting services fixes it. But hoping that comes sooner rather than later so I can just get on board with minimal effort.

**Comment by aleemb** [comment]
I was not aware of the syslog limitations, makes sense. I would miss out on the stack trace with these services at the very least.

**Comment by tuupola** [comment]
UDP is fire and forget. You just send the packet and keep fingers crossed it reaches the destination. Time sending an UDP packet is so small user will not even notice it. But this is of course just theory, since Bugsnag does not support UDP endpoints.

```bash
$ time /bin/sh -c 'echo "foo" | nc -c -w 1 -u api.bugsnag.com 8125'
0.013u 0.003s 0:00.01 100.0%	0+0k 0+0io 0pf+0w
```

**Comment by aleemb** [comment]
On my side of the world (Asia),

```
$ time /bin/sh -c 'echo "foo" | nc -c -w 1 -u api.bugsnag.com 8125

real	0m1.782s
user	0m0.004s
sys	0m0.010s
```

**Comment by tuupola** [comment]
Also in Asia :) Anyways the -w 1 flag actually waits for one second so my example is a bit flawed.

**Comment by aleemb** [comment]
You're right, talking to someone more familiar with UDP I was told it's really 0.782 (subtracting 1) but even there netcat arguments I am passing are incorrect (I am using OpenBSD version on Ubuntu & OSX which are different from the version you are using).

**Comment by it-can** [comment]
I always use this, maybe it will help...

```
$options = [
    CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4
];
$bugsnagClient->setCurlOptions($options);
```

**Comment by GrahamCampbell** [comment]
We've fixed the curl handing issue now.

**Comment by alfredbez** [comment]
> The way I get around this issue is to push the logs to a queue and have the logging done async by a queue worker.

@GrahamCampbell We use bugsnag in our high-traffic shop and we're planning to integrate something like gearman. Is there a way to dispatch a job for [unhandled exceptions](https://docs.bugsnag.com/platforms/php/other/#reporting-unhandled-exceptions) with [automatically captured diagnostics](https://docs.bugsnag.com/platforms/php/other/#automatically-captured-diagnostics)?

**Comment by GrahamCampbell** [comment]
Instead of using our handler, you could implement your own that used your app's queue system to report, that'd be totally fine.

Another option (probably better) would be to override our transport implementation, and instead add your own that queues instead of sending over http. What I'd recommend doing here is actually injecting your own custom implementation of `GuzzleHttp\ClientInterface` into our `Bugsnag\HttpClient` object. I'll write you some example code in a second. :)

**Comment by GrahamCampbell** [comment]
So, using the 2nd option is definitely the way to go, because you get to use all the library features, then just delay the actual http transport part.

```php
// $key = getenv('BUGSNAG_API_KEY');
// $key = 'your-key-or-whatever';

// $client = your custom implementation of GuzzleHttp\ClientInterface

$bugsnag = new Bugsnag\Client(new Configuration($key), null, $client);
Bugsnag\Handler::register($bugsnag);
```

Actually, the only method on the guzzle client interface you need to implement is the `post` method, which we call here: https://github.com/bugsnag/bugsnag-php/blob/master/src/HttpClient.php#L158.

Just stub out all the methods of https://github.com/guzzle/guzzle/blob/5.3/src/ClientInterface.php or https://github.com/guzzle/guzzle/blob/master/src/ClientInterface.php, whichever you have installed (you can find out by running `composer show -i`), then just implement the `post` method, to send the json data, and URL to your queue, so you can handle it as you want.

**Comment by GrahamCampbell** [comment]
I actually wish we'd instead had another layer of abstract here, with respect to transport, but we didn't want to overdo it, making the library so complex to understand, so the way to get custom transport methods, is just to stub the guzzle contract used by our http client (used by our "client).

**Comment by alfredbez** [comment]
Awesome thanks! :+1:
