### ISSUE TITLE
src/Bugsnag/Request.php:35: Error in exception handler: array_merge():

### ISSUE THREAD

**Issue by Ralla** [bugsnag/bugsnag-php#116]
This breaks if ```$requestData['request']['params']```is not an array.

```
if(isset($requestData['request']['params'])) {
    $requestData['request']['params'] = array_merge($requestData['request']['params'],$params);
}
```

May I suggest:

```
if (isset($requestData['request']['params']) && is_array(isset($requestData['request']['params']))) {
    $requestData['request']['params'] = array_merge($requestData['request']['params'],$params);
}
```

**Comment by kattrali** [comment]
Thank you for the report and suggestion, @Ralla. Taking a look.

**Comment by Volind** [comment]
Maybe it's better to check why you're getting such situation:

`$requestData['request']['params'] = json_decode(file_get_contents('php://input'));`

json_decode returns object instead array. We could add second parameter to its call:

`$requestData['request']['params'] = json_decode(file_get_contents('php://input'), true);`

**Comment by kattrali** [comment]
@Volind Ah! That was it. I looked at it a few times I didn't notice it wasn't being converted into an associative array. Patching.
