### ISSUE TITLE
Reporting of a JSON object request crashes

### ISSUE THREAD

**Issue by Blizzke** [bugsnag/bugsnag-php#120]
I have a couple requests where a JSON object is PUTed  (`{"general":{}}` for the simplest possible example).
When that fails and ends up with BugSnag, it passes through the `Request::getRequestMetaData()` and [it gets decoded into an `\stdClass` instance](https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Request.php#L28).

[A couple lines farther](https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Request.php#L35) an attempt is made to `array_merge()` this `\stdClass` with the `parse_str()` version of that same JSON and that causes an exception to be thrown ("Argument \#1 is not an array).

Perhaps adding the decode as an array option could help out here?

**Comment by realshadow** [comment]
I have the same problem, sadly I had to discover it in production

**Comment by PhiloNL** [comment]
Same issue here

**Comment by kattrali** [comment]
Thank you for the report, @Blizzke. Fixed in [2.7.1](https://github.com/bugsnag/bugsnag-php/blob/master/CHANGELOG.md#271-2016-06-02).
