### ISSUE TITLE
Refactor to use guzzle

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-php#146]

**Comment by GrahamCampbell** [comment]
Maybe we should instead use Httplug? This gives users more flexibility, but, is harder to setup.

**Comment by kattrali** [comment]
I think they are about equal from a dependency weight standpoint, and as long as we fix a few key things, I'm fine with either. Requirements:

* Remove a number of hacks related to uploading reports such as 
  [handling cURL headers](https://github.com/bugsnag/bugsnag-php/blob/3ce4f0cf893832c093e3addf82514e028d76aaea/src/Bugsnag/Notification.php#L116) ([#115](https://github.com/bugsnag/bugsnag-php/pull/115), [relevant blog post](http://the-stickman.com/web-development/php-and-curl-disabling-100-continue-header/)) and 
  [parsing request contents](https://github.com/bugsnag/bugsnag-php/blob/95d91c7fbd13ff0bf392d70ef06449b56e6fcbe7/src/Bugsnag/Request.php#L27) ([#92](https://github.com/bugsnag/bugsnag-php/issues/92))
* Improve performance by enabling asynchronous upload without having to deal with PHP threading ([#114](https://github.com/bugsnag/bugsnag-php/issues/114))

**Comment by GrahamCampbell** [comment]
> I think they are about equal from a dependency weight standpoint

Using httpplug will have significantly more dependencies. Since we'd need all that, and then guzzle on top.

**Comment by kattrali** [comment]
Would we still need guzzle though with the basics provided by httplug?

**Comment by GrahamCampbell** [comment]
Yes, or something else that httplug allows us to use as a driver. httplug is only giving us wrappers around guzzle, and the others.

**Comment by GrahamCampbell** [comment]
> and parsing request contents (#92)

That one's unrelated to this. I can fix that on master pretty easily.

**Comment by GrahamCampbell** [comment]
Done.
