### ISSUE TITLE
Add test for checking that the user information is in the payload

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-php#195]

**Comment by GrahamCampbell** [comment]
There is no way to mock the payload using phpunit's mocking due to the stack trace.

**Comment by GrahamCampbell** [comment]
Just tried it

**Comment by GrahamCampbell** [comment]
We can probably do it using spys though. I'm not entirely sure if this will work on PHP 5.2. I guess we'll find out.

**Comment by kattrali** [comment]
Hmm, well at least then we'll know.
