### ISSUE TITLE
Tags / release install

### ISSUE THREAD

**Issue by it-can** [bugsnag/bugsnag-php#223]
Hi,

I installed bugsnag with this command.
```composer require "bugsnag/bugsnag:2.*"```

But it doesnt install the latest tag/version, it will always install the latest commit. When I run the command now I get this.

```
composer require "bugsnag/bugsnag:2.*"

- Installing bugsnag/bugsnag (dev-master f2bd181)
Cloning f2bd1816182432317dd1e871d8418d8595aa2625
```

I expected version v2.9.0 (#332b322)

Is there something I am doing wrong?

**Comment by GrahamCampbell** [comment]
It looks like your have your minimum stability set to `dev`. You are getting the latest version, just not the latest tag.

**Comment by it-can** [comment]
aaah ok, will check..
