### ISSUE TITLE
Allow `setProjectRoot` to accept an array of project paths

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-php#29]
It is common to have code running from multiple locations on your server. Eg:

1. `/var/www/`
2. `/apps/myapp`

Both of these paths could be considered `inProject` but it is currently difficult for people to set multiple project root paths.

I propose we enhance `setProjectRoot` to accept a PHP `array` of paths, and to increase the prominence of this setting in the readme.

Bonus points if we can somehow automatically set project roots in a smarter way.

**Comment by kattrali** [comment]
Holding on this in favor of a broader pass of PHP library improvements.
