### ISSUE TITLE
Bugsnag documentation for Laravel is incorrect.

### ISSUE THREAD

**Issue by base-zero** [bugsnag/bugsnag-php#294]
On the docs [page](http://docs.bugsnag.com/platforms/php/laravel/) you have the following code snippet for installing bugsnag into Laravel.

```
'providers' => [
    // ...
    Bugsnag\BugsnagLaravel\BugsnagLaravelServiceProvider::class,
    // ...
],
```

However the latest version the BugsnagLaravelServiceProvider class doesn't exist as such the code block should be.

```
'providers' => [
    // ...
    Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,
    // ...
],
```

**Comment by GrahamCampbell** [comment]
Thank you very much for the report. I'll get this fixed right away.

**Comment by GrahamCampbell** [comment]
The fix has been deployed now.
