### ISSUE TITLE
Don't just overwrite global error & exception handlers

### ISSUE THREAD

**Issue by nedt** [bugsnag/bugsnag-php#301]
In our website we show "pretty" error pages for fatal PHP error or uncaught exceptions. Adding bugsnag with the standard handler `Bugsnag\Handler::register($bugsnag);` showed blank pages instead, because our handlers were simply overwritten.

It should at least be an option to have the old error and exception handlers be called, i.e. with a second parameter $chainHandlers, which may default to false.

**Comment by GrahamCampbell** [comment]
Right, yeh, You should only call `Handler::register()` if you want to override the error handlers. PHP doesn't have a way to chain error handlers I think?

**Comment by GrahamCampbell** [comment]
For custom usage, you can just make your own Handler class, and then use our Client however you want.

**Comment by nedt** [comment]
_Sorry for the late response, but maybe someone else has the same problem._

Thing is I try to avoid copying code, that's why I'd like to use `\Bugsnag\Handler::register()`. Just because it isn't doing much know, doesn't mean it'll always be this way.

And I'm not in charge of the overall framework, which is Typo3, so I can't control the other error handlers.

Instead I've created a helper function, which I now use around `\Bugsnag\Handler::register()`.

```
/**
 * calls a register function that might change the error and/or exception handler
 * and creates a wrapper handler that calls both.
 *
 * @param callable $registerFn inside this function the error or exception handlers need to be registered
 */
function chainErrorHandlers($registerFn) {
  if (!is_callable($registerFn)) {
    throw new \InvalidArgumentException('$registerFn is not a valid callback');
  }

  $noop = function () {};

  $old_error_handler = set_error_handler($noop);
  restore_error_handler();
  $old_exception_handler = set_exception_handler($noop);
  restore_exception_handler();

  $registerFn();

  if ($old_error_handler) {
    $new_error_handler = set_error_handler($noop);
    restore_error_handler();
    if ($old_error_handler !== $new_error_handler) {
      set_error_handler(function () use ($old_error_handler, $new_error_handler) {
        call_user_func_array($old_error_handler, func_get_args());
        call_user_func_array($new_error_handler, func_get_args());
      });
    }
  }

  if ($old_exception_handler) {
    $new_exception_handler = set_exception_handler($noop);
    restore_exception_handler();
    if ($old_exception_handler !== $new_exception_handler) {
      set_exception_handler(function () use ($old_exception_handler, $new_exception_handler) {
        call_user_func_array($old_exception_handler, func_get_args());
        call_user_func_array($new_exception_handler, func_get_args());
      });
    }
  }
}
```

Usage:
```
chainErrorHandlers(function () {
  \Bugsnag\Handler::register();
});
```
