### ISSUE TITLE
Filter the request

### ISSUE THREAD

**Issue by pedrosalpr** [bugsnag/bugsnag-php#321]
I wonder how I do to filter some request keys?

Like, I did not want to appear "Host" in the Request tab?

There are a combination of functions, in order to amplify the setFilters function, to be able to accept filter array of arrays
Eg.:
`$bugsnag->setFilters(array('request' => array('Host','Origin'), 'cookie'));`

**Comment by GrahamCampbell** [comment]
You should be able to add a callback that deletes the host from the request data. Alternatively, for a really custom implementation, you can pass through your own request resolver to the constructor of the client.
