### ISSUE TITLE
Installation documentation for Laravel - optional vendor:publish step is actually required

### ISSUE THREAD

**Issue by andzandz** [bugsnag/bugsnag-php#325]
Hi,

On this page https://docs.bugsnag.com/platforms/php/laravel/ it is stated:

> If you’d like to configure Bugsnag further, create and edit a configuration file:
> 
> ```
>    $ php artisan vendor:publish
> ```

This step is actually required for Bugsnag to be able to find your API key from your .env file - you must have a bugsnag.php file in the config directory. If you do not do this step, you will get "API key not found" errors.

Quite a small detail of the docs but took a little while to figure out, so please correct. Cheers!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but you shouldn't have to publish the config file to get this working. Did you remember to run `php artisan config:cache`?

**Comment by andzandz** [comment]
Hi, thanks for the reply. Nice project, Bugsnag is useful.

I didn't run `php artisan config:cache` - I'll try it on a fresh project later (quite busy lately). If it is required, please add to the guide.

Cheers

**Comment by GrahamCampbell** [comment]
It's required on all laravel projects whenever you want to update the config. We could add it to the guide to remind people though.

**Comment by GrahamCampbell** [comment]
I can't replicate this on any Laravel version. it must be due to not correctly caching the config files.
