### ISSUE TITLE
[proposal] Allow use of guzzlehttp/guzzle:^5.0||^6.0 for project with older dependencies.

### ISSUE THREAD

**Issue by okaufmann** [bugsnag/bugsnag-php#329]
Is it possible to allow guzzle 5.x as well for older projects? 

Since this is a bug collector and guzzle is just the http client, it would be great to not block Projects using older versions of guzzle while require only 6.0.

What do you think?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. We can definitely look into it. I avoided it originally because the two work completely differently, so we'd need entirely different code to set them up.

**Comment by okaufmann** [comment]
Ok, thank you

**Comment by GrahamCampbell** [comment]
Out of interest, what is it that's stopping you from upgrading to guzzle 6? Is there a specific part of guzzle 5 you need?

**Comment by okaufmann** [comment]
There are other Dependencies like https://github.com/php-tmdb/api using older versions of guzzle.

I think it's a philosophy-question. Push all other dependencies to use newest packages and support only newest versions of php or make own packages more flexible. 

For that reason this issue is a proposal to be discussed :sweat_smile:

**Comment by GrahamCampbell** [comment]
Ok, thanks. I'm working on this right now. :)

**Comment by GrahamCampbell** [comment]
How does https://github.com/bugsnag/bugsnag-php/pull/332 look please @okaufmann?

**Comment by okaufmann** [comment]
I've made a test install from the ´guzzle´ branch wich worked for me.

![image](https://cloud.githubusercontent.com/assets/4414498/17363414/998ba3c6-597a-11e6-8844-8a651a5eaf81.png)

Will use it from ´bugsnag-laravel´ right after it was merged.

Thanks for your lightning support!

**Comment by GrahamCampbell** [comment]
If you want to test it out with our laravel package, what you can do is this:

```json
    "require": {
        "bugsnag/bugsnag": "dev-guzzle as 3.2.0",
        "bugsnag/bugsnag-laravel": "^2.1"
    },
```

Note that will only temporarily work, just like your other fix. It'll stop working once we merge this into the codebase.

**Comment by okaufmann** [comment]
Thanks! I'll test it later today.

**Comment by okaufmann** [comment]
It worked for me. Thanks again for the fast support!

When will this approx be merged ?

**Comment by GrahamCampbell** [comment]
I don't really know at this point I'm afraid. We're reviewing quite a few PRs on the open source scene at the moment, with quite a few of them on the PHP libraries. I would hope that this would be in the develop branch by the end of the week, but I can't promise anything.

Do let me know if you have any questions about any part of the library.

**Comment by okaufmann** [comment]
I found a little configuration bug in the bugsnag laravel package I just fixed.

Please review the PR: https://github.com/bugsnag/bugsnag-laravel/pull/160

Hope it helps.

**Comment by GrahamCampbell** [comment]
Thanks. :)
