### ISSUE TITLE
Unhandled recoverable errors inadvertently being recovered by BugSnag

### ISSUE THREAD

**Issue by itafroma** [bugsnag/bugsnag-php#360]
In `BugSnag\Handler::register()`, `BugSnag\Handler::errorHandler()` is registered as an error handler.

However, it does not return `false`, so it prevents any additional error handling after BugSnag handles the error, including the default error handling behavior in PHP, which is to treat otherwise-unhandled `E_RECOVERABLE_ERROR`s as `E_ERROR`s by stopping execution.

I was wondering what the rationale was behind this, or if this was simply an oversight.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This looks like it could be a proper solution to #301.

**Comment by GrahamCampbell** [comment]
I've created a PR to address this.

**Comment by itafroma** [comment]
Awesome! One additional thing we found was that while returning false will allow the default error handling to pick up after BugSnag, it doesn't allow custom error (or exception) handling to take place since you can only have one error/exception handler active at a time.

Instead, what we did was extend `BugSnag\Handler` and use it instead:

```
use BugSnag\Handler;

class CustomHandler extend Handler
{
    /**
     * {@inheritdoc}
     */
    public function exceptionHandler($throwable)
    {
        parent::exceptionHandler($throwable);

        // Our custom exception handling here
    }

    /**
     * {@inheritdoc}
     */
    public function errorHandler($errno, $errstr, $errfile = '', $errline = 0)
    {
        parent::errorHandler($errno, $errstr, $errfile, $errline);

        // Our custom error handling here

        return false;
    }
}
```
