### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by e98cuenc** [bugsnag/bugsnag-php#369]
in HttpClient.php line 98 there is a call to $this->postJson, but this method doesn't exist in HttpClient, the closest method is called postJSON.

Is this a bug?

I can't get my errors in bugsnag even when I rename postJson to postJSON.

**Comment by GrahamCampbell** [comment]
PHP method calls aren't case sensitive, however, that is an inconsistency that probably needs addressing. The casing of a method call is likely unrelated to your issue.

You can debug the state of the Bugsnag client by calling the `getApiKey()` method on the `Client` instance you have, to check the correct API key is loaded.
