### ISSUE TITLE
 Pass variables into the function of adding callbacks?

### ISSUE THREAD

**Issue by pedrosalpr** [bugsnag/bugsnag-php#370]
How do I pass the metadata and severity variables into the function, to be included in the report?

Because I have a class where it has a function and I pass parameters the metadata and severity variables to be sent to Bugsnag.

```
$bugsnag->notifyException($exception, function (Bugsnag\Report $report){
    $report->setMetaData($metadata);
    $report->setSeverity($severity);
});
```

**Comment by GrahamCampbell** [comment]
You'll need to use php's way of binding variables to a closure.

```php
$bugsnag->notifyException($exception, function (Bugsnag\Report $report) use ($metadata, $severity) {
    $report->setMetaData($metadata);
    $report->setSeverity($severity);
});
```

Where those variables are defined already. Or, implement your own function that you can call within the Closure to generate these values.

Please let me know if I've interpreted your question correctly?

**Comment by pedrosalpr** [comment]
That's what I needed. Thank you.

You could add this in the documentation,it would help a lot other developers.

**Comment by GrahamCampbell** [comment]
I'm hesitant to suggest adding this to the documentation since it's unrelated to Bugsnag IMO. It's just a feature included in PHP. Example 3 on the PHP docs shows usage of the `use` construct with Closures: https://secure.php.net/manual/en/functions.anonymous.php.

**Comment by pedrosalpr** [comment]
Thank you.
