### ISSUE TITLE
use default error handler for non-notify-release-stage?

### ISSUE THREAD

**Issue by mfurlend** [bugsnag/bugsnag-php#377]
Thanks for all your hard work on bugsnag. It is a great platform/service. 
I have bugsnag set to notify on staging and production release stages:

```PHP
define('ENVIRONMENT',get_environment()); //DEVELOPMENT||STAGING||PRODUCTION
$bugsnag_config->setReleaseStage(ENVIRONMENT);
$bugsnag_config->setNotifyReleaseStages([STAGING, PRODUCTION]);
```
When I am working on a development release I would like bugsnag to pretend like it's not there at all, and to use the default error handler (var_dump, or whatever).
I can't seem to figure out a way to do this.

I can simply avoid instantiating bugsnag when `ENVIRONMENT===DEVELOPMENT`, but that seems... meh.

Any tips?

**Comment by GrahamCampbell** [comment]
What you can do is conditionally register our error handler.

**Comment by GrahamCampbell** [comment]
Are you using the latest release? The error handler registration, and the bugsnag client have been totally separated, so this is easy to do.
