### ISSUE TITLE
Allow injection as an optional dependency/null-object pattern: Bugsnag\Client does not implement an interface

### ISSUE THREAD

**Issue by dominics** [bugsnag/bugsnag-php#383]
I'd like to be able to use the 'null object' pattern with Bugsnag, especially for cases in which notification is optional. That way, I don't have to pepper my code with `if ($this->bugsnag !== null)` checks that increase cyclomatic complexity and make test coverage harder to attain. In other words, I'd:

 - Configure my object with a NullClient that has the same public methods (e.g. `notifyException()`) as a real client
 - Use setter injection to replace this with a real client on the fly depending on whether I want to allow Bugsnag notification

However, the Bugsnag client doesn't implement any interface, so I can't replace the concrete Bugsnag instance with a non-functional equivalent (there's no interface to type-hint against other than the concrete implementation :cry:)

As a feature, this library could allow usage in roughly the same way that PSR3 does (i.e via a ClientAwareInterface/ClientAwareTrait/ClientInterface combination), thereby making usage as an optional dependency super-easy. Alternatively, you could _just_ implement an interface, and let the user decide how they'd like their null implementation to work.

At the moment, the workaround for a null-object requires you to extend Bugsnag\Client (which is a bit of an LSP violation perhaps)

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. The recommended option here would be to set the release stage config so that your testing or development environments don't notify Bugsnag, if that's what you want.

Is there any specific area where that method is causing you problems? I'd be interested to know, to see how we can improve things. :)

**Comment by dominics** [comment]
I am already using the release stage config options. I'm also thinking specifically of classes that want to call `notifyException()` on a handled exception (don't have a problem with the catch-all handlers for uncaught errors/exceptions).

In my use-case, the real advantage of an interface is that the class doing the notifying can be instantiated without a real `Bugsnag\Client` instance - the client can become an optional dependency. And I still don't need to null-check the member property every time I go to use it.

What's the difference between a "real" Bugsnag client that is disabled by the release stage config and a "null" client (or any other implementation of a `Bugsnag\ClientInterface`)? Well, for a start, the config (project root, app version, etc.) is required for instantiating the former, but not necessarily for the latter. Also, it gives the user of the library the ability to "null out" the client on *any* criteria, not just the environment.

Finally, using an interface also would let someone extend the client by composition rather than only by concrete inheritance. (Quite nice!)

**Comment by GrahamCampbell** [comment]
One way around this I can think of, is to use our psr-3 logger?

**Comment by dominics** [comment]
I don't particularly like the Bugsnag PSR-3 logger. (Off topic why, but while "implementors MAY have special handling for [__toString() objects passed as $message]", the more usual way to pass exceptions to a logger IMO is to use the 'exception' context key explicitly mentioned in the spec: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#13-context - so it'd miss 90% of my handled/logged exceptions anyway)

I'm also already using aggregate loggers (a la MultiLogger) for my own purposes. And using a generic LoggerInterface means you can't choose which exceptions go to Bugsnag if you only want to send some of them (while retaining full logging to e.g. Monolog). It's all-or-nothing on the per-LoggerAwareInterface-instance level.

What do you think about the 'allows extension by composition' argument? AFAICT, that's the reason why most PHP client libraries will include an interface, even if they only provide one implementation of it. (e.g. https://github.com/nrk/predis/blob/v1.1/src/ClientInterface.php or https://github.com/guzzle/guzzle/blob/master/src/ClientInterface.php)

**Comment by GrahamCampbell** [comment]
> I don't particularly like the Bugsnag PSR-3 logger. (Off topic why, but while "implementors MAY have special handling for [stringable objects passed as $message]", the more usual way to pass exceptions to a logger IMO is to use the 'exception' context key explicitly mentioned in the spec: 

Laravel has a habit of passing exceptions as messages to psr loggers, and the bugsnag logger supports this too, so that there's no loss of information. So, if you want to abuse the psr logger to get abstraction, it is technically possible.

> What do you think about the 'allows extension by composition' argument?

Definitely something to consider if/when bugsnag-php v4 is designed perhaps? One other thing to note about having a client interface for the main class, is we are quite restricted in what we can do. Adding new parameters to methods, and adding new methods, become major breaking changes.

> Edit: also wanted to mention your PHP stuff is still lightyears ahead of a certain other error monitoring company

Thanks. :)

**Comment by GrahamCampbell** [comment]
The other problem we have, is we use dynamic calls, that we cannot make part of the interface, unless we changed everything to be hard coded methods.

**Comment by GrahamCampbell** [comment]
All things considered, I don't think there's any scope to make changes right now, however, I'll definitely keep your ideas in mind for possible future changes, thanks!
