### ISSUE TITLE
Fatal error: Class 'Bugsnag' not found

### ISSUE THREAD

**Issue by gdhnz** [bugsnag/bugsnag-php#386]
According to the [advanced docs](https://docs.bugsnag.com/platforms/php/other/advanced-client-configuration/), you can use Bugsnag::ENDPOINT to get the endpoint.

This fails with ```Fatal error: Class 'Bugsnag' not found``` on v3.5.1.

I had to use ```Bugsnag\Client::ENDPOINT``` instead.

**Comment by GrahamCampbell** [comment]
Very sorry about that. That seems to be a typo in the docs. Should read as `Bugsnag\Client::ENDPOINT`.

**Comment by GrahamCampbell** [comment]
This has been fixed now.
