### ISSUE TITLE
No setAutoNotify in v3

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-php#391]
This was useful in certain conditions (e.g. local development), and I don't see a way to have a empty bugsnag instance that does nothing. I certainly need an initialized object for `setUser` and other calls to succeed without erroring out.

**Comment by GrahamCampbell** [comment]
This has been replaced by setting the release stages you want to notify. See https://docs.bugsnag.com/platforms/php/other/configuration-options/#release-stage. By default Bugsnag always notifies, but if you only want to notify on production, you could set:

```php
$bugsnag->setNotifyReleaseStages(['production']);
```

where by you have done something like this too:

```php
$bugsnag->setReleaseStage('local');
```

**Comment by GrahamCampbell** [comment]
> No setAutoNotify in v3

If you don't want to "auto notify" in exactly the same way, then you should not register the "error handler". That is actually the direct mapping from v2 to v3.

**Comment by GrahamCampbell** [comment]
Architecturally, from v2 to v3, the error handler registration is totally separate from the Bugsnag client class now.

**Comment by xPaw** [comment]
Changing release stages sounds good enough to me, thanks!

**Comment by GrahamCampbell** [comment]
👍
