### ISSUE TITLE
Does not work in command line

### ISSUE THREAD

**Issue by polmartinez** [bugsnag/bugsnag-php#394]
I use both, in fuelphp framework and in an isolated php and the library does not log the exceptions. Only print a dump of the report object.

**Comment by GrahamCampbell** [comment]
I think what's happening here is that batch mode is turned on?

**Comment by polmartinez** [comment]
No, in both mode

       $bugsnag = \Bugsnag\Client::make("c6268f72666bc53c12624714f46cc9d1");
       $bugsnag->setBatchSending(false);
       Bugsnag\Handler::register($bugsnag);

![tmp_ _root_server-01___home_ubuntu_and_does_not_work_in_command_line_ _issue__394_ _bugsnag_bugsnag-php](https://user-images.githubusercontent.com/1065284/28747382-b3267bc8-749d-11e7-828c-f3470ea4f9c7.png)

**Comment by GrahamCampbell** [comment]
Does the demo app in the example folder work with your api key please?

**Comment by polmartinez** [comment]
fixed.
Was a framework problem. Fuelphp does not let you manage the logs and errors well, and something was happening in the core. I had to use notifyException
Thanks

**Comment by GrahamCampbell** [comment]
Should be possible to get fuelphp to call this function. In the context of frameworks, you don't want to use bugsnag's own handler, rather, just get the framework to call bugsnag, similar to the silex notifier. :)
