### ISSUE TITLE
registerWithPrevious()

### ISSUE THREAD

**Issue by Spotnyk** [bugsnag/bugsnag-php#415]
Am I attempting to use this incorrectly?

`$bugsnag = \Bugsnag\Client::make("KEY");`
`$bugsnag->setErrorReportingLevel( E_ALL );`
`\Bugsnag\Handler::registerWithPrevious($bugsnag);`

When attempting this code, I get: `Call to undefined method Bugsnag\Handler::registerWithPrevious()`

To be clear, this code works just fine if I use `register` instead of `registerWithPrevious`

I am running v3.8.1

**Comment by GrahamCampbell** [comment]
It looks like you don't have v3.8.1. Can you check the contents of the file please, and see if it has the code in? It's also possible that PHP has cached the file internally - you may need to restart php-fpm.

You can find exactly which file php is using by doing the following:

```php
var_dump((new \ReflectionClass(\Bugsnag\Handler::class))->getFileName());
```

**Comment by Spotnyk** [comment]
@GrahamCampbell You're right. It was being cached. I've never actually had this issue before (10+ years). Maybe it's a phar thing?

Will `opcache_reset()` do that for me in the future?
