### ISSUE TITLE
Object properties being dropped in Metadata

### ISSUE THREAD

**Issue by Cawllec** [bugsnag/bugsnag-php#422]
### Expected behavior
Objects given as metadata get parsed into JSON and shown in the Bugsnag dashboard as a tab.

### Observed behaviour
It trims object data off the payload instead at [this json_encode](https://github.com/bugsnag/bugsnag-php/blob/master/src/Report.php#L661)

### Additional information
Referred from [Bugsnag-PSR-Logger](https://github.com/bugsnag/bugsnag-psr-logger) issue [#25](https://github.com/bugsnag/bugsnag-psr-logger/issues/25)

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by Cawllec** [comment]
@gyurobenjamin, I'm don't think what you are describing is supported behaviour.  The cleanup function ensures that data is json encodable before we attempt to send it in the payload.  In this case the object properties are being dropped as the native PHP function drops them when it converts the Exception objects into JSON.

```php
php > $e = new Exception("Issue");
php > echo $e;
Exception: Issue in php shell code:1
Stack trace:
#0 {main}
php > echo is_object($e);
1
php > $j = json_encode($e);
php > echo $j;
{}
```

As such this functionality isn't suitable for sending exception objects into bugsnag.  Instead that should be done using the `notifyException` method on the `Client` object.  This will correctly extract the data from the `Exception` object to populate the payload.

If you still want to attach exception data manually I'd suggest looking at the `fromPHPThrowable` factory function on the [`Report` object](https://github.com/bugsnag/bugsnag-php/blob/c359f5dc81b808acc8238f4c14d1261c7dbc53b0/src/Report.php)

**Comment by gyurobenjamin** [comment]
I use a custom Log facade in laravel. This helps me to use the \Log::method() in the code with bugsnag.

So the whole project has been written with thousands of \Log::method('message', [$data]). This data could be response with guzzle, model objects, exceptions or anything else.

These methods trigger two codes, bugsnag and monolog. We used to use only monolog, and that is able to format objects nicely.

Please have a look at this: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php

**Comment by Cawllec** [comment]
Ok, using callbacks it's actually not too difficult to use monologs own formatter to format the data for sending using callbacks.  As an example in flat PHP:

```php
<?php

require_once "vendor/autoload.php";

$client = Bugsnag\Client::make('API_KEY');

$logger = new Bugsnag\PsrLogger\BugsnagLogger($client);

$client->registerCallback(function($report) {
    $normalizer = new Monolog\Formatter\NormalizerFormatter();
    $currentMetaData = $report->getMetaData();
    $formattedMetaData = $normalizer->format($currentMetaData);
    $report->setMetaData($formattedMetaData, false);
});

$exception = new Exception("This is my exception");

$logger->error("An exception occurred", [$exception]);
```

This will take each report, format it using the monolog formatter, then overwrite the current metadata with the formatted data.  In Laravel I believe this would go in your `AppServiceProvider/boot` function.

**Comment by gyurobenjamin** [comment]
Thank you @Cawllec, this will be fine for now. Tested and worked well.
