### ISSUE TITLE
notifyException not reporting Exceptions in CLI environment

### ISSUE THREAD

**Issue by nathansams** [bugsnag/bugsnag-php#469]
### Expected behavior
*notifyException() method should report handled exceptions when run in a CLI environment.*

### Observed behavior
*Although unhandled Exceptions are reported to Bugsnag, manually caught and handled exceptions are not being reported in a CLI environment when using the notifyException method.*

### Steps to reproduce
```$bugsnag = \Bugsnag\Client::make(env('BUGSNAG_API_KEY'));
\Bugsnag\Handler::register($bugsnag);

try {
	throw new \Exception("This is a test");
} catch (\Exception $e) {
	$bugsnag->notifyException($e); // This isn't reported
}
```

### Version
*3.12.1*

### Additional information
*I've tried various things to get handled reporting working in a CLI environment, but nothing seems to be working.*

**Comment by snmaynard** [comment]
Can you test out our examples - probably notify.php in https://github.com/bugsnag/bugsnag-php/tree/master/example/php to see if they work for you? I tested it just now and it worked for me. Then if that works we can compare with your CLI to see what differences there are.

**Comment by nathansams** [comment]
Thanks for that. Ok so it works using those barebones scripts.

Why would unhandled exceptions be reported in my app CLI environment but manually notifying Bugsnag, even immediately after initialising the Bugsnag client not work. E.g.

```
$bugsnag = \Bugsnag\Client::make();
\Bugsnag\Handler::register($bugsnag);

try {
	throw new RuntimeException('Something went wrong'); // Not reported
} catch (\Exception $e) {
	$bugsnag->notifyException($e);
}
```

but this IS reported:

```
```
$bugsnag = \Bugsnag\Client::make();
\Bugsnag\Handler::register($bugsnag);

throw new RuntimeException('Something went wrong');
```

**Comment by Cawllec** [comment]
Hi @nathansams, I'm not entirely certain why this is happening at the moment.  Would you be able to give me any more information about the environment your app is running in i.e. are you using a framework such as Laravel or Symfony, how are you configuring Bugsnag, etc.

**Comment by Cawllec** [comment]
@nathansams, I'm closing this for now, but if you continue to have the issue please let me know and I'll re-open this.
