### ISSUE TITLE
Implement collectUserIp just like in bugsnag-js

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-php#480]
It would be nice if there was a simple way of turning off IP collection just like the JS library recently added.

**Comment by Cawllec** [comment]
Hi @xPaw, you can manually override any collected IPs within bug reports using callbacks:
```
$bugsnag->registerCallback(function ($report) {
  $report->setUser([
    "id" => null // Replaces the automatically collected IP
  ]);
  $report->setMetaData([
    "request" => [
      "clientIp" => null // Replaces the automatically collected IP
    ]
  ]);
});
```
These are the two places we currently put client IP address in the payload.

We currently don't have plans to add IP collection toggling as in the JS notifier as that was a platform specific issue that needed to be resolved, which is not a factor in the PHP notifiers.

**Comment by xPaw** [comment]
Interesting. Is the `setUser` necessary if `setMetaData` is set? As far as I know user id gets set to the value of clientIp by default.

**Comment by Cawllec** [comment]
The users `id` property is set separately to the `request` metadata.  While they're both resolved from the same place, they are resolved separately and will both need to be overridden.

**Comment by xPaw** [comment]
Well I deployed the code you suggested, however it seems that IP in `request` tab still gets logged somehow, even though `id` in `user` did get set to `null`.

**Comment by xPaw** [comment]
This seems like a worthwhile idea to add this snippet to examples/documentation.

**Comment by xPaw** [comment]
That fix does indeed work, however I just noticed that there's IP headers (from cloudflare), so need to hide headers too.

**Comment by GrahamCampbell** [comment]
Perhaps a better approach would be to whitelist the headers you're interested in, rather than to blacklist ones you want to avoid recording?

**Comment by xPaw** [comment]
To be honest I haven't found headers all that useful, in my case I could just remove them.

**Comment by Cawllec** [comment]
HI @xPaw, I'm closing this for now.  If the issue reoccurs, or if there are any others, please create a new issue here.
