### ISSUE TITLE
Singleton?

### ISSUE THREAD

**Issue by kw-pr** [bugsnag/bugsnag-php#490]
I would like to call `$bugsnag->notify()`, `$bugsnag->notifyException()`, ... from inside a class to handle catched errors and do other stuff. If I didn't miss anything I currently have to add the $bugsnag object to all my classes, make $bugsnag `global`, or create a second client with the same config but not sure what would...

It would be nice to have a singleton to get the current client.

As a workaround I created this:

    class BugsnagSingleton
    {
        /** @var \Bugsnag\Client|null */
        protected static $instance = null;

        public static function setInstance($instance)
        {
            static::$instance = $instance;
        }

        /**
         * @return \Bugsnag\Client
         */
        public static function getInstance()
        {
            return static::$instance;
        }
    }
    BugsnagSingleton::setInstance($bugsnag);

That could be used this way:

    BugsnagSingleton::getInstance()->notifyError('test', 'test');

**Comment by Cawllec** [comment]
Hi @kw-pr, thanks for the suggestion.  I've raised this to our products team, and update you ASAP.

**Comment by GrahamCampbell** [comment]
I'd be very much against Bugsnag's PHP library shipping with the client as singleton. It's a massive antipattern that lots of legacy PHP projects use, and voids all testability. Instead, you should inject an instance of the bugsnag notifier into the classes where you need to use them.

If you want a singleton instance, you can easily construct one yourself with a couple of lines of code, thus it doesn't need to be in the package core. In fact, I see that's exactly what you've done. That would be the correct solution if you don't want to use DI as far as I can see: to create the class in your app and not have it in this library.

**Comment by GrahamCampbell** [comment]
Honestly, if you have a bugsnag variable in most of your classes, I'd say this is a bit of a code smell? Could you refactor to avoid this. That is, are your classes doing too much. Can error handling be moved higher up the chain?

**Comment by snmaynard** [comment]
Giving people the option of using a singleton wrapper seems sensible. We have a similar pattern in Android as an example and we shouldn't be in the business of being code police for other projects. Sometimes singletons can make sense for people and it seems low risk to add.

**Comment by Cawllec** [comment]
I tend to agree, if users want this feature they should probably implement it themselves as I doubt any approach we take would be suitable across all the possible singleton implementations.  I do wonder if there's anything we can do to point to singletons as a solution in a PHP app.

In the `installation` section of Laravel we discuss using an alias or importing Bugsnag into all the areas you wish to use it.  Perhaps a similar section could be added to the vanilla PHP documentation, pointing to a resource on writing singletons in PHP possibly?

**Comment by Cawllec** [comment]
I think we've agreed we won't be adding a singleton method, to avoid enforcing particular pattern usage on users, closing this issue.
