### ISSUE TITLE
StyleCI not working

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-php#531]
I noticed StyleCI was unable to analyze the PR I just sent, because the access token has either been revoked, or third party access controls are preventing access:

> remote: Permission to bugsnag/bugsnag-php.git denied to kattrali. fatal: unable to access 'https://[REDACTED]@github.com/bugsnag/bugsnag-php.git/': The requested URL returned error: 403

**Comment by snmaynard** [comment]
I dont see any mention of it in the admin settings - I believe it was using @kattrali's token - maybe theres something in your settings to enable/disable? Or we can get @tomlongridge to configure it now?

**Comment by kattrali** [comment]
I'm not sure what's happening. On our end, the webhook is firing and there's even an activity item for @GrahamCampbell's PR in the logs.

**Comment by GrahamCampbell** [comment]
Looking at the settings, it's configured to automatically send fixes as PRs, and then once the tests complete (or sooner if the branch is not protected), it will attempt to squash merge the PRs: https://github.styleci.io/repos/7568230/settings.

It looks like @kattrali's token's no longer valid, since the API calls to set the commit status are also failing with 404. This can be fixed by simply logging out and in again.

**Comment by GrahamCampbell** [comment]
The other thing that could explain why the token is not working would be the third party access control settings... Ah yes, it seems the bugsnag organization has not granted access to StyleCI: https://github.com/settings/connections/applications/65b53dad3d9ba5f49b3c.

**Comment by kattrali** [comment]
You figured it out just before I did. Permissions were revoked/changed at some point.

**Comment by snmaynard** [comment]
Theres nothing in there saying its been denied - maybe we need to request again so it shows up to be approved?

**Comment by snmaynard** [comment]
Approved now - @kattrali requested again

**Comment by GrahamCampbell** [comment]
By default, GitHub will not allow access I think. I'm not sure what the timescale for this was, since when they first introduced it, I don't think they enforced things on existing organizations to avoid breaking everything.

**Comment by GrahamCampbell** [comment]
That seemed to work. I just re-triggered an analysis of master. :)
