### ISSUE TITLE
Packagist hooks need updating

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-php#533]
GitHub has deprecated the legacy service hooks system, in favour of webhooks. Bugsnag's PHP packages are not yet using the new hooks.

![image](https://user-images.githubusercontent.com/2829600/59974845-99452280-95a8-11e9-9919-26817b590670.png)

Luckily, there is an easy fix. @kattrali simply needs to visit https://packagist.org/trigger-github-sync/. Since you're both an admin on the repos on GitHub, and marked as an maintainer on packagist, packagist will be able re-setup the webhooks using your access token. (also, one should check that packagist has third-party access on GitHub)

**Comment by kattrali** [comment]
fixed! thanks @GrahamCampbell
