### ISSUE TITLE
Consider using phpstan (or another analyser) on the codebase

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-php#593]
phpstan and psalm are great static analysers that help find various issues.

In particular, bugsnag has quite a few wrong phpdocs, with one example being `@return string|null` in `getRequestIp`, but it only returns strings on isset, and there is no return null (it returns void instead).

**Comment by steve-nester-uk** [comment]
@xPaw thanks for the suggestion, we're going to discuss internally.
