### ISSUE TITLE
Unable to modify breadcrumbs from registerCallback

### ISSUE THREAD

**Issue by MakerTim** [bugsnag/bugsnag-php#658]
Hey Team BugsnagPHP,

I'm currently unable to modify breadcrumbs.
We send a lot of breadcrumbs, but they contain sensitive data.
To sanatize them is hard to detect and replace, so we only want them sanatized on sending errors and not while adding breadcrumbs.

Could we get access to breadcrumbs?
E.g. a getBreadcrumbs with assosiative array's

I can make a proposal implementation, but first I want to hear what you think about this idea.

kind regards
Tim

**Comment by natepage** [comment]
@MakerTim Hi! We've faced a similar situation in different projects and agree that sanitizing data within breadcrumbs is a bit tricky with the current implementation. It would be nice to see an easier way to do it in this package directly, in the meantime here is the code we are using to do so.

It's a little "magic" as we are using a closure that we bind to the report instance to modify the value of its `$breadcrumbs` property but it works 😄 

```php
// Our own sanitizer service
$sanitizer = $this->sensitiveDataSanitizer;

// Call registerCallback on Client
$bugsnag->registerCallback(static function (Report $report) use ($sanitizer): void {
    // First we sanitise the metadata of the report itself
    $report->setMetaData($sanitizer->sanitize($report->getMetaData()), false);

    // Fetch breadcrumbs from report array representation
    $breadcrumbs = $report->toArray()['breadcrumbs'] ?? [];
    $redactedBreadcrumbs = [];

    // Build our own breadcrumbs array with sanitized data
    foreach ($breadcrumbs as $breadcrumb) {
        if (isset($breadcrumb['metaData'])) {
            $breadcrumb['metaData'] = $sanitizer->sanitize($breadcrumb['metaData']);
        }

        $redactedBreadcrumbs[] = $breadcrumb;
    }

    // Override the value of $breadcrumbs property on report using bound closure
    (function ($property, $value): void {
        $this->{$property} = $value;
    })->call($report, 'breadcrumbs', $redactedBreadcrumbs);
});
```

**Comment by johnkiely1** [comment]
Going to close this out as there are a couple of workaround options suggested above.
