### ISSUE TITLE
New Relic PHP extension causes duplicate errors in BugSnag

### ISSUE THREAD

**Issue by benzeghers-bold** [bugsnag/bugsnag-php#660]
### Describe the bug
The New Relic PHP extension registers an exception handler before BugSnag. Bugsnag-php calls the previous exception handler but since it does not rethrow the exception, `$enableShutdownHandler` is not set to `false`.  This causes duplicate errors in BugSnag, one from the exception handler and one from the shutdown handler. 

### Environment
bugsnag-php version: v3.29.0
PHP version: 8.1
New Relic daemon version: 10.0.0.312-9fd43b56a296

### Steps to reproduce

1. Install New Relic PHP agent: https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-overview/
2. Run the following PHP script:
```php
<?php

$bugsnag = Bugsnag\Client::make();
Bugsnag\Handler::register($bugsnag);

throw new Exception('Uncaught Exception');
```
3. The exception thrown will show up in BugSnag twice:
![image](https://user-images.githubusercontent.com/98761454/234120720-8de3bdb1-e20d-4af7-b833-3449afe2ed02.png)

**Comment by johnkiely1** [comment]
Closing this out, as we haven't heard back from you. Happy to reopen as necessary.
