### ISSUE TITLE
Add support for headers when using nginx

### ISSUE THREAD

**Issue by arthens** [bugsnag/bugsnag-php#76]
https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Request.php#L34

The function `getallheaders` is not available when using php-fpm. 
https://bugs.php.net/bug.php?id=62596

Maybe the client could define it's own function?
http://php.net/manual/en/function.getallheaders.php#84262

**Comment by ConradIrwin** [comment]
@arthens This what our ruby notifier does — I'd love to see a pull request to make it work for anyone using php-fpm :).
