### ISSUE TITLE
setSendCode significantly slows execution time

### ISSUE THREAD

**Issue by jstayton** [bugsnag/bugsnag-php#78]
Hey guys,

When I recently updated from v2.3.0 to v2.5.0, I found that PHP execution time of my app became significantly slower. It averaged 150ms with v2.3.0, but saw nothing faster than 350ms with v2.5.0.

I _think_ the culprit is `setSendCode`. When I set that to `false`, execution time returns to ~150ms. Is that expected? It's easy enough to set it to `false`, but my feeling is something's off.

This is with PHP v5.3.11.

Thanks!

**Comment by jstayton** [comment]
Here's the code I'm using:

```php
$bugsnag = new Bugsnag_Client('MY_API_KEY');
set_error_handler(array($bugsnag, 'errorHandler'));
set_exception_handler(array($bugsnag, 'exceptionHandler'));
$bugsnag->setReleaseStage('MY_RELEASE_STAGE');
$bugsnag->setErrorReportingLevel(E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR);

// Not sure if it matters, but I do register a shutdown function to redirect to an error page when there's an exception.
register_shutdown_function(function () {
  $error = error_get_last();

  // All error types to handle. Warnings are ignored.
  $errorTypes = array(E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR);

  if (!empty($error) && in_array($error['type'], $errorTypes)) {
    header('Location: /error.php');
  }
});
```

To be clear, the slowdown is seen regardless of whether there's an error or not.

**Comment by ConradIrwin** [comment]
@jstayton Thanks for this! I think the problem is that we get the stacktrace and all the code even in the case when we ignore the warnings. I'll try and fix this in the next few days.

**Comment by jstayton** [comment]
Thanks, @ConradIrwin!

**Comment by nricca** [comment]
Hi,
what about the "fix in the next few days" ?
We use the 2.5.4 and you still create the stacktrace for warnings.
Regards

**Comment by monptitjojo** [comment]
Same problem we had a temporary ugly fix

**Comment by jessicard** [comment]
Hey @monptitjojo, @nricca & @jstayton - so sorry about the wait! I'm taking a look into this now, and I will make sure we get a fix out for this in the next week.

**Comment by loopj** [comment]
Just released v2.5.5 of bugsnag-php which now correctly skips any unnecessary Bugsnag code if the error should be ignored!

**Comment by nricca** [comment]
Thanks !!

**Comment by jstayton** [comment]
:star: Thanks!

**Comment by monptitjojo** [comment]
Thanks a lot
