### ISSUE TITLE
Add direct support for monolog log handling

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-php#89]
Symfony has dependency injection for common logging services:
https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/Configuration.php

**Comment by Zae** [comment]
Hey @loopj,

I just published [monolog-bugsnag](https://github.com/Zae/monolog-bugsnag) which is a monolog handler that will send the logged messages to bugsnag.

**Comment by kattrali** [comment]
Closing out in favor of the Monolog community library.
