### ISSUE TITLE
JSON data doesn't populate request if php://input has already been read

### ISSUE THREAD

**Issue by jcherniak** [bugsnag/bugsnag-php#92]
In PHP prior to 5.6, [you can only read php://input one time](http://php.net/manual/en/wrappers.php.php#wrappers.php.input).  Thus if your code has read it before an exception is thrown, the request parameters will not be filled in.

I'm unsure of good options.  In my particular use case (Yii2 framework), I can manually edit Bugsnag_Request:;getRequestMetaData to get the raw post body from Yii::$app->request->getRawBody() since that caches it, but that isn't a general solution.

**Comment by GrahamCampbell** [comment]
Hi @jcherniak. Sorry for the long wait. https://github.com/bugsnag/bugsnag-php/pull/194 should fix this issue for you.
