### ISSUE TITLE
Check if host has curl enabled during deployment

### ISSUE THREAD

**Issue by jessicard** [bugsnag/bugsnag-php#93]
Bugsnag can fail during a deployment because even if curl is installed, a host can have it it disabled. I'm not sure the function_exists check is the best option for determining how to submit a notification.

**Comment by jacobmarshall** [comment]
Do you know which hosts (for example). I'll check them out and see what we
can do. I understand it may differ from hosts, so I'm willing to try as
many as it takes :P

On Fri, 31 Jul 2015 at 6:15 am jessicard <notifications@github.com> wrote:

> Bugsnag can fail during a deployment because even if curl is installed, a
> host can have it it disabled. I'm not sure the function_exists check is the
> best option for determining how to submit a notification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-php/issues/93>.
>
-- 
Regards,
Jacob

*Email:* jacob@manage.net.nz
*Phone:* (+64) 21 026 940 83

**Comment by jessicard** [comment]
@jacobmarshall You are the *best* for looking at this! :heart: I don't have any examples, but you should be able to disable curl on any host you're using afaik.

**Comment by jacobmarshall** [comment]
Yeah, you're right. For some dumb reason I assumed there was some other
sneaky way of disabling curl :P
On Fri, 31 Jul 2015 at 6:37 am jessicard <notifications@github.com> wrote:

> @jacobmarshall <https://github.com/jacobmarshall> You are the *best* for
> looking at this! [image: :heart:] I don't have any examples, but you
> should be able to disable curl on any host you're using afaik.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-php/issues/93#issuecomment-126427776>.
>
-- 
Regards,
Jacob

*Email:* jacob@manage.net.nz
*Phone:* (+64) 21 026 940 83

**Comment by kattrali** [comment]
The implementation of this has changed somewhat since July, will revisit if this ever persists.
