### ISSUE TITLE
Users cant set their own userid in metadata

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-php#96]
This -> https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Error.php#L157 -> can overwrite user id passed through with metadata.

**Comment by GrahamCampbell** [comment]
We don't support setting the user id using the metadata. You need to set the user, specifically, which is different. In some situations, it will work though, due to how bugsnag's backend will process it (ie, when there was no "user" set originally, it'll look at the metadata.

**Comment by snmaynard** [comment]
I dont see how I can configure a user as a part of a notify -> http://docs.bugsnag.com/platforms/php/other/reporting-handled-errors/

**Comment by GrahamCampbell** [comment]
http://docs.bugsnag.com/platforms/php/other/#identifying-users

**Comment by GrahamCampbell** [comment]
;)

**Comment by GrahamCampbell** [comment]
What is the use case for setting it as part of calling notify?

**Comment by GrahamCampbell** [comment]
Surely people will normally be calling bugsnag through a logging abstraction anyway?

**Comment by GrahamCampbell** [comment]
I guess we could support setting the user on the error object on master.

**Comment by GrahamCampbell** [comment]
Here we go @snmaynard: https://github.com/bugsnag/bugsnag-php/pull/209. Sorry about the misunderstanding!
