### ISSUE TITLE
Make retrieval of server variables pluggable

### ISSUE THREAD

**Issue by atrauzzi** [bugsnag/bugsnag-php#99]
We're currently using bugsnag on a google app engine application using Laravel.

Unfortunately, the following line is causing us some issues: https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Request.php#L62

Now, given that this isn't bugsnag-laravel, I understand that we can't leverage any of the configuration or request/response libraries.  Although it would be ideal if the mechanism used to obtain values like these was pluggable.  Then, bugsnag-laravel could ship an implementation that retrieves the variables from its own abstraction.  Then, bugsnag-php can ship defaults that use the superglobals.

**Comment by GrahamCampbell** [comment]
Thanks. I definitely plan to get this implemented in v3.

**Comment by GrahamCampbell** [comment]
Going to implement this using a request resolver to resolve a request object.

**Comment by GrahamCampbell** [comment]
If there's no request, we can have a nulled object.

**Comment by GrahamCampbell** [comment]
Will land in 3.x shortly.
